# Generated by Django 4.0.1 on 2022-01-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
